// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ8-i4p9CZE4P0xHCr2XtYQj_K9T4CWLw',
    appId: '1:1012629903941:web:da7e0205aba9be969b212c',
    messagingSenderId: '1012629903941',
    projectId: 'behealthy-e17ad',
    authDomain: 'behealthy-e17ad.firebaseapp.com',
    storageBucket: 'behealthy-e17ad.firebasestorage.app',
    measurementId: 'G-R1THR3SGB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FmHiLh9w1sbf-fOWAjlUJDKd1da8Z6A',
    appId: '1:1012629903941:android:d3d0b5cc252b1c259b212c',
    messagingSenderId: '1012629903941',
    projectId: 'behealthy-e17ad',
    storageBucket: 'behealthy-e17ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2H249MYacJ4g1KoE3CzkhYNjAaS8tKs',
    appId: '1:1012629903941:ios:26fe8d2a0d85743b9b212c',
    messagingSenderId: '1012629903941',
    projectId: 'behealthy-e17ad',
    storageBucket: 'behealthy-e17ad.firebasestorage.app',
    iosBundleId: 'com.example.beHealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq2H249MYacJ4g1KoE3CzkhYNjAaS8tKs',
    appId: '1:1012629903941:ios:26fe8d2a0d85743b9b212c',
    messagingSenderId: '1012629903941',
    projectId: 'behealthy-e17ad',
    storageBucket: 'behealthy-e17ad.firebasestorage.app',
    iosBundleId: 'com.example.beHealthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ8-i4p9CZE4P0xHCr2XtYQj_K9T4CWLw',
    appId: '1:1012629903941:web:5559509b4c7ac5de9b212c',
    messagingSenderId: '1012629903941',
    projectId: 'behealthy-e17ad',
    authDomain: 'behealthy-e17ad.firebaseapp.com',
    storageBucket: 'behealthy-e17ad.firebasestorage.app',
    measurementId: 'G-2C32XHWVH9',
  );
}



